version = 0.1

[default.deploy.parameters]
stack_name = "my-lambda-stack"
resolve_s3 = true
s3_prefix = "my-lambda-stack"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
